### ISSUE TITLE
what is  Binary Classified Pain Images/0 ?

### ISSUE THREAD

**Issue by wangyu-bit** [Trailblazer29/Pain-Detection-From-Facial-Expressions#1]

**Comment by Trailblazer29** [comment]
Thanks for your question @wangyu-bit.

The original dataset was structured in a sequential way (i.e. each video recording for each patient was stored in a separate folder, in which there might be frames belonging to different classes). 

In order to load the data with Pytorch's **DataLoader**, I altered the dataset's structure by putting all frames belonging to the same class, in the same folder, thus having exclusive class folders. **Binary Classified Pain Images/0** is the path of the subfolder in which there are "no-pain" frames only (Class 0).
